### ISSUE TITLE
New icon proposal

### ISSUE THREAD

**Issue by AlexejheroYTB** [Qwiso/QModManager#11]
I propose a new icon for the next QModManager update (1.3). It looks really great in my opinion

Icon created by `WhitePaw#5358`

![ico](https://user-images.githubusercontent.com/32238504/43004064-42f8db54-8c37-11e8-9b55-cbb45b4fa202.png)

**Comment by AlexejheroYTB** [comment]
If this icon is accepted, the next version number should be 2.0 instead of 1.3

**Comment by AlexejheroYTB** [comment]
(Work in progress, will be discussed on the main PR)
Anyway, the next update will have log changes, and mod.json changes (Requires removed, LoadAfter and LoadBefore added (+ paradox checks))

**Comment by RandyKnapp** [comment]
I put a lot of thought into the icon. It's the Braille symbol for 'Q'.

I don't "approve" of the new icon, I'm sorry. It feels meaningless and changing the icon would disassociate the new version from old mods.

**Comment by AlexejheroYTB** [comment]
Oh, I did not know!
It's alright then
