### ISSUE TITLE
Thoughts about the next update

### ISSUE THREAD

**Issue by AlexejheroYTB** [Qwiso/QModManager#12]
In the next update, I am thinking about implementing a `LoadBefore` and `LoadAfter` system, which will completely replace `Requires`. The only issue is that it could lead to paradoxes (for example, mod `A` wants to load before `B`, `B` before `C`, and `C` before `A`)
I know to detect paradoxes, but the question is what do I do if one is found? 

1. Mod `A` gets loaded before `B`, `B` before `C`, and `C` after (ignoring order - could cause issues)
2. Mod `A` gets loaded before `B`, then `B`, and `C` doesn't get loaded at all (to avoid issues)
3. All 3 mods don't get loaded (to not favorize some mods over others based on an alphabetic order)
(In all cases, an error is outputted in the console)

This will not replace `Priority`! If a mod with an `Other` priority needs to load after a mod with `Last` priority, that won't happen! But yet again, what should happen?

1. `Other` mod gets loaded before `Last` mod (ignoring order - could cause issues)
2. `Other` mod doesnt get loaded (to avoid issues)
(In all cases, an error is outputted in the console)

**Comment by RandyKnapp** [comment]
I really appreciate the work you doing to take over this software, Alexejhero.

**Comment by AlexejheroYTB** [comment]
I'm not trying to take it over. I'm just trying to improve it

**Comment by Qwiso** [comment]
I'm glad that there is someone else to motivate progress. I'd never have released or updated this repo without each of you supporting it. Ditto, AlexejheroYTB. I appreciate it

**Comment by AlexejheroYTB** [comment]
Oh and uh, I really like that icon in #11, but I don't know if I should use it or not (for TerraTech). If I do, the icons won't be the same for all games (I'd like to keep it the same across games), but if I don't, all his hard work would be wasted. Any suggestions @randyknapp?

**Comment by AlexejheroYTB** [comment]
Still want to know your guys' opinion on what should happen

**Comment by AlexejheroYTB** [comment]
I'd really like to know your guys' opinion on what should happen if a paradox is detected
