### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Commissar0617** [Qwiso/QModManager#14]
i see the qmods folder, and the mods option in game, but buttan does nothing.

**Comment by AlexejheroYTB** [comment]
First of, please research before making issues. The "Mods" button is not from QModManager, but from Modding Helper 2.0.
Secondly, if you see the QMods folder, it means that it works.

**Comment by AlexejheroYTB** [comment]
This is not a QModManager issue, it's an issue with another mod. Closing...

**Comment by AlexejheroYTB** [comment]
To clarify: the button wasn't working because you didn't have any mods that had settings installed.
