### ISSUE TITLE
[Suggestion] Repository merge

### ISSUE THREAD

**Issue by AlexejheroYTB** [Qwiso/QModManager#16]
This is just a suggestion, that I would like you to think about. 
Merging the two repositories into one would make things a lot easier since changes could be done only once and a "Game" parameter could be set through the installer

**Comment by AlexejheroYTB** [comment]
@ahk1221 @PrimeSonic @RandyKnapp @Qwiso @Aceba1 @weskey007
I hope the pings don't bother you. If they does, just tell me and I won't ping you next time.

**Comment by AlexejheroYTB** [comment]
If this is done, there would be no point in having the organization, so it would be deleted

**Comment by PrimeSonic** [comment]
Before we commit to something like this, it would be helpful to first identify all the "game specific" areas in the code that would need to be handled by the "game parameter". 

It would also be important to define how the final installer will function and if there would be any risk for players installing QModManager for both supported games.

**Comment by AlexejheroYTB** [comment]
The only place where a game parameter is required is in the patch method which is only required for terratech
The installers would be separate, and they would have their own unique identifier, so there won't be any issues.

**Comment by PrimeSonic** [comment]
So with that in mind, I would suggest the following:  

1. Let's prepare a third repo, preferably with whatever shared access is needed for all people involved.
2. In that repo we begin the "Unified QModManager" solution
3. Once that build is ready for use by both mods, the other two can be repos can be depreciated (or merged if that makes more sense)

The point I'm stressing is to have the distinct repos coexisting with the unified repo until the unified repo is ready to replace both original repos.

I would recommend that the unified solution use custom build configurations to selectively compile the code specific to Subnautica or TerraTech.

**Comment by AlexejheroYTB** [comment]
Still, it's up to @Qwiso to decide

**Comment by AlexejheroYTB** [comment]
@PrimeSonic The Unified QModManager repo could just be one of the existing repos. 

I researched a lot about inno setup and I think I can make it only one installer which detects what game you are trying to install it for
