### ISSUE TITLE
Mac Version?

### ISSUE THREAD

**Issue by bglemoine** [Qwiso/QModManager#5]
Desperately need a Mac version - anything on the horizon for that?

**Comment by AlexejheroYTB-acc** [comment]
Unfortunately, there are no plans (that I know of) for mac support. The author of the mod is no longer active in the subnautica modding community, and there will be no updates in the foreseeable future

**Comment by AlexejheroYTB-acc** [comment]
I will reply to this issue as soon as I have more information

**Comment by AlexejheroYTB** [comment]
@bglemoine There is a user on the subnatica modding discord who has managed to create a mac version for qmodmanger (you can join here: https://discord.gg/DNXdeGA)

**Comment by AlexejheroYTB** [comment]
His tag is `Zebralear#6081`

**Comment by AlexejheroYTB** [comment]
@Zebralear

**Comment by AlexejheroYTB** [comment]
His discord tag is `Zebralear#6081` and his github name is @Zebralear

**Comment by Zebralear** [comment]
Here you go @bglemoine! Enjoy Modded Subnautica!
https://github.com/Qwiso/QModManager/blob/master/Mac%20Installation

**Comment by AlexejheroYTB** [comment]
👍

**Comment by AlexejheroYTB** [comment]
Just a note: not all mods are compatible!

**Comment by Cairneann** [comment]
Unfortunately, I can't use the method written by @Zebralear because I'm presented with an error "Cannot open assembly 'QModsSetup.exe': File does not contain a valid CIL image." Any ideas what could cause this and how to fix it?

**Comment by AlexejheroYTB** [comment]
#18
