### ISSUE TITLE
it wont work at all

### ISSUE THREAD

**Issue by tanker122** [Qwiso/QModManager#6]
i can seem to get any mods to work with subnautica, i have a windows 10 and i can install it, but i cant seem to intall the mods correctly, i need help, anyway to get a step by step guide? bc im not finding any

**Comment by legojoshua12** [comment]
Did you make sure to unzip the mods before putting them in the QMods folder?

**Comment by tanker122** [comment]
yes i did

**Comment by AlexejheroYTB-acc** [comment]
Please post a screenshot with the structure of your QMods folder

**Comment by AlexejheroYTB** [comment]
@tanker122

**Comment by AlexejheroYTB** [comment]
Will close in 48 hours
