### ISSUE TITLE
An example mod for QModManager

### ISSUE THREAD

**Issue by the-vindicar** [Qwiso/QModManager#9]
A simple example of how to develop a QModManager-compatible mod would be appreciated. 
What's written in README.md is a nice start, but it leaves a few questions open, like how to link up Subnautica's assemblies, how to see which objects are available, etc.
The content can be really minimalistic, like writing a line into game log at the start.

**Comment by AlexejheroYTB** [comment]
Look at other mods for examples

**Comment by AlexejheroYTB** [comment]
...or, join the subnautica modding discord! https://discord.gg/DNXdeGA
